name: geomagcubes
channels:
  - conda-forge
dependencies:
  # Jupyter dev environment
  # These are optional if you have 
  - jupyterlab=3.2
  - pyviz_comms=2.1
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyter-lsp-python
  - jupyter-resource-usage
  # Dependencies for this project
  - python=3.8
  - pip
  - cython
  - ipykernel
  - ipywidgets
  - numpy=1.22
  - scipy=1.7
  - matplotlib=3.4
  - pandas=1.3
  - xarray=0.20
  - dask=2021.11
  - aiohttp=3.8
  - intake=0.6
  - intake-xarray=0.6
  - cartopy=0.20
  - pytables=3.6
  - h5py=3.1
  - netcdf4=1.5
  - tenacity=8.0
  - zarr=2.11
  - hvplot=0.7
  - datashader=0.13
  - pooch=1.6
  - geoviews=1.9
  # For ML
  - scikit-learn=1.1
  - tensorflow=2.7
  # # For vaex & ipyvolume
  # - gcc
  # - ipyvolume
  # - vaex
  # required for saving holoviews objects
  - selenium=4.1
  - firefox
  - geckodriver
  - pip:
    - viresclient==0.10.3
    - hapiclient==0.2.4
    - chaosmagpy==0.9
    - -e .
# variables:
#   HDF5_USE_FILE_LOCKING: "FALSE"
platforms:
  - linux-64
